:source-highlighter: highlightjs

= Hello, AsciiDoc

Doc Writer <doc@example.com>

An introduction to
http://asciidoc.org[AsciiDoc]








== First Section
* item1
* item2
** item3



== First Order Logic
- Gestione dei quantificatori
- Le formule vengono trasformate in formula prenessa
  - Motivo: I quantificatori innestati complicano l'infrastruttura del programma
    e causano problemi sulla gestione della quantita' di memoria disponibile
    EG: Iterazione per colonna VS iterazione per riga su una Matrice 2D
  - La macchina lavora come uno stack scegliendo una combinazione di valori
    e svolgendo operazioni e pushando i risultati e poppando gli operandi sullo
    stack




[background-video="./videos/fractal.webm", options="loop,muted"]
== Recursion!

== Prova prova
- Some text

== DPLL Solver
- Dato un AST che viene richiesto dall'utente segue una fase di preprocessazione
  in cui ogni singola clausola viene convertita come serie di NAND.
- Il solverl DPLL risolve un AST composto interamente e solamente da operatori NAND
  da letterali e da costanti
- Boolean toggling di una variabile per capire se per un dato
  operatore NAND per fare il satisfy dell'intera formula serve a dire se `a NAND b`
  a, b devono condividere lo stesso valore oppure devono essere diversi

- NOTA BENE: a NAND a = NOT a, se iterando troviamo che per satisficare l'intera
  formula serve che a NAND a abbia childs con valori opposti, la formula non
  e' verificabile.

- Parlare di come si puo' verificare la dipendenza di determinati letterali o meno
  all'interno della formula se dopo l'esecuzione si trova che a un particolare
  letterale presente all'interno dell AST non e' stato necessario assegnare alcun valore
  specifico.